/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PillRouteImport } from './routes/pill'
import { Route as WorkMapsIndexRouteImport } from './routes/work-maps.index'
import { Route as WorkMapsIdRouteImport } from './routes/work-maps.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PillRoute = PillRouteImport.update({
  id: '/pill',
  path: '/pill',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkMapsIndexRoute = WorkMapsIndexRouteImport.update({
  id: '/work-maps/',
  path: '/work-maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkMapsIdRoute = WorkMapsIdRouteImport.update({
  id: '/work-maps/$id',
  path: '/work-maps/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pill': typeof PillRoute
  '/work-maps/$id': typeof WorkMapsIdRoute
  '/work-maps/': typeof WorkMapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pill': typeof PillRoute
  '/work-maps/$id': typeof WorkMapsIdRoute
  '/work-maps': typeof WorkMapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pill': typeof PillRoute
  '/work-maps/$id': typeof WorkMapsIdRoute
  '/work-maps/': typeof WorkMapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pill' | '/work-maps/$id' | '/work-maps/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pill' | '/work-maps/$id' | '/work-maps'
  id: '__root__' | '/' | '/pill' | '/work-maps/$id' | '/work-maps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PillRoute: typeof PillRoute
  WorkMapsIdRoute: typeof WorkMapsIdRoute
  WorkMapsIndexRoute: typeof WorkMapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pill': {
      id: '/pill'
      path: '/pill'
      fullPath: '/pill'
      preLoaderRoute: typeof PillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-maps/': {
      id: '/work-maps/'
      path: '/work-maps'
      fullPath: '/work-maps/'
      preLoaderRoute: typeof WorkMapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-maps/$id': {
      id: '/work-maps/$id'
      path: '/work-maps/$id'
      fullPath: '/work-maps/$id'
      preLoaderRoute: typeof WorkMapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PillRoute: PillRoute,
  WorkMapsIdRoute: WorkMapsIdRoute,
  WorkMapsIndexRoute: WorkMapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
